teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 4
      y: 3
      z: 7
    scale_linear:
      x: 0.4
      y: 0.4
      z: 0.4
    axis_angular:
      yaw: 6
      pitch: 0
      roll: 1
    scale_angular:
      yaw: 0.5
      pitch: 0.5
      roll: 0.5
    enable_button: 5
    enable_turbo_button: -1
